# coding: utf-8

# flake8: noqa
"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from ni_custom_client.models.scaling_info import AutoScaler
from ni_custom_client.models.scaling_info import DQN_ScalingInfo
